---
title: "Untitled"
author: "Murray Cadzow"
date: "11/11/2019"
output: html_document
params:
  pop: "nph"
  trait: "HEIGHT"
---

```{r setup}
library(tidyverse)
library(here)
ggplot2::theme_set(theme_bw())

if(params$trait != ""){
  trait <- params$trait
} else {
    #trait <- 'HEIGHT' # default test case
}

if(params$pop != ""){
  pop <- params$pop
} else {
  #pop <- 'nph'
}

```


### GCTA
```
# GCTA dir
parallel 'cat {} |tr -s " " | tr " " "\t" > {}.tsv' ::: *hsq
```


```{r, warning = FALSE, message = FALSE}
# this will cause warning messages because the files essentially are missing the last column in the bottom rows
hsq_files <- fs::dir_ls(path = here("results/",paste0(pop,"_",trait),"GCTA"), glob = "*.hsq.tsv")
hsq <- purrr::map(hsq_files, read_tsv) %>% set_names(str_remove_all(hsq_files, here(paste0("results/",pop,"_",trait,"/GCTA//"))))
```


compare h2 with lowest lowest SE and significant P
```{r}
gcta_extract <- function(hsq_df, name){
  Pval = hsq_df %>% filter(Source == "Pval") %>% pull(Variance)
  h2_var = hsq_df %>% filter(Source == "V(G)/Vp") %>% pull(Variance)
  h2_se = hsq_df %>% filter(Source == "V(G)/Vp") %>% pull(SE)
  return(tibble("file" = name,"pval" = Pval, "h2_var" = h2_var, "h2_se" = h2_se))
}

gcta_models <- purrr::map_dfr(names(hsq), ~gcta_extract(hsq[[.x]], .x ))

gcta_models <- gcta_models %>% mutate(significant = ifelse(pval < 0.05, TRUE, FALSE),
                                      cv = str_extract(file, "cv[1-5]"),
                                      model_n = str_extract(file, "_([0-9])+") %>% str_remove_all("_") %>% as.numeric()) 

gcta_models %>% ggplot(aes(x = h2_se, y = h2_var, colour = significant)) + geom_point() + ggtitle("significant models") + coord_cartesian(ylim = c(0,1), xlim = c(0,1))



gcta_models %>% filter(max(h2_var)== h2_var)
```

```{r}
gcta_models %>% ggplot(aes(x = h2_se, y = h2_var, colour = factor(model_n))) + geom_point() + ggtitle("Coloured by Model") + coord_cartesian(ylim = c(0,1), xlim = c(0,1)) + facet_wrap(~cv)
```

```{r}
gcta_models %>% ggplot(aes(x = h2_se, y = h2_var, colour = cv)) + geom_point() + ggtitle("Coloured by Model") + coord_cartesian(ylim = c(0,1), xlim = c(0,1)) + facet_wrap(~model_n) 
```

### LDAK

```
parallel 'grep "^Her\|^Com" {} > {}.h2' ::: *.reml
parallel 'grep "^LRT_P" {} > {}.p' ::: *.reml
```


```{r, warning = FALSE, message = FALSE}
ldak_files <- fs::dir_ls(path = here("results/",paste0(pop,"_",trait),"/LDAK"), glob = "*.reml.h2")
ldak <- purrr::map(ldak_files, read_delim, delim = ' ') %>% set_names(str_remove_all(ldak_files, here(paste0("results/",pop,"_",trait,"/LDAK/"))))

ldak_p_files <- fs::dir_ls(path = here(paste0("results/",pop,"_",trait,"/LDAK")), glob = "*.p")
ldak_p <- purrr::map(ldak_p_files, ~ read_delim(.x, delim = " ", col_names = c("stat", "lrt_p"))) %>% 
  set_names(str_remove_all(ldak_p_files, here(paste0("results/",pop,"_",trait,"/LDAK/"))))

ldak <- purrr::map_dfr(names(ldak), ~ ldak[[.x]] %>% mutate(file = str_remove(.x, ".h2")))
ldak_p <- purrr::map_dfr(names(ldak_p), ~ ldak_p[[.x]] %>% mutate(file = str_remove(.x, ".p")) %>% select(-stat))

ldak_models <- ldak %>% left_join(ldak_p, by = "file") %>% 
  filter(Component == "Her_ALL") %>% 
  rename(h2_var = Heritability, h2_sd = Her_SD) %>% 
  mutate(cv = str_extract(file, "cv[1-5]"), 
         model_n = str_extract(file, "_([0-9])+") %>% str_remove("_") %>% as.numeric(),
         significant = ifelse(lrt_p < 0.05, TRUE, FALSE)
         )
```


```{r}
ldak_models %>% ggplot(aes(x = h2_sd, y = h2_var, colour = significant)) + geom_point() + ggtitle("significant models") + coord_cartesian(xlim = c(0,1)) 
```

```{r}
ldak_models %>% ggplot(aes(x = h2_sd, y = h2_var, colour = factor(model_n))) + geom_point() + ggtitle("Coloured by Model") + coord_cartesian(ylim = c(0,1), xlim = c(0,1)) + facet_wrap(~cv)
```

```{r}
ldak_models %>% ggplot(aes(x = h2_sd, y = h2_var, colour = cv)) + geom_point() + ggtitle("Coloured by Model") + coord_cartesian(ylim = c(0,1), xlim = c(0,1)) + facet_wrap(~model_n) 
```


## BayesR

